import './globals.css'
import { Inter } from 'next/font/google'
import { Metadata } from "next";
import React from "react";
import Script from 'next/script'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '欢迎来到德莱联盟',
  keywords: "edhqdqwhd",
  description: 'Generated by create next apwwwwwwwwwwwwp',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Script id="my-script" dangerouslySetInnerHTML={{
      __html: `
        (function(para) {
          if(typeof(window['sensorsDataAnalytic201505']) !== 'undefined') {
            return false;
          }
          window['sensorsDataAnalytic201505'] = para.name;
          window[para.name] = {
            para: para
          };
        })({
          server_url: "https://test-syg.datasink.sensorsdata.cn/sa?token=27f1e21b78daf376&project=lixiang", // 'https://sc-sa.dzfread.cn/sa?project=W_test',
          is_track_single_page: false, // !important
          name: 'Sensors',
          cross_subdomain: false, // 不同域名不同用户
          use_client_time: true,
          send_type:'ajax', // ajax beacon
          // heatmap: {}, // 全埋点
          show_log: true, // 设置 true 后会在网页控制台打 logger，会显示发送的数据,设置 false 表示不显示。
        });`
    }} />
    <Script id="my-script2" src="/sensorsdata.js" />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
