import './globals.css'
import { Inter } from 'next/font/google'
import { Metadata } from "next";
import React from "react";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '欢迎来到德莱联盟',
  keywords: "edhqdqwhd",
  description: 'Generated by create next apwwwwwwwwwwwwp',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
