import React from "react";
import type { Metadata, NextPage } from "next";
import { netHomeData } from "@/server/home";
import TestCom from "@/components/test";
interface IProps {}

export const metadata: Metadata = {
  title: '欢迎来到德莱联盟222test',
  keywords: "edhqdqwhd",
  description: 'Generated by create next apwwwwwwwwwwwwp',
}

const Test: NextPage<IProps> = () => {

  const SendMessage = async () => {
    console.log('1212121')
    const a = await netHomeData();
    console.log(a);
  }
  return (
    <TestCom/>
  )
}

export default Test;
